apiVersion: v1
kind: Service
metadata:
  name: wilkystorm
  namespace: default
  labels:
    app: wilkystorm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: wilkystorm
